<?php

namespace Sr\NotesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    /**
     * Retourne les tâches qui sont toujours ouvertes
     * @return mixed
     */
    public function findTachesOuvertes() {
        $em = $this->getEntityManager();
        /** @var $q \Doctrine\ORM\Query */
        $q = $em->createQuery("SELECT n FROM SrNotesBundle:Note n WHERE n.type = :type AND n.pcAvancement < 100");
        $q->setParameters(array('type' => Note::TYPE_TACHE));
        $r = $q->getResult();
        return $r;
    }

    /**
     * Retourne les projets ouverts
     * @return array
     */
    public function findProjetsOuverts() {
        $em = $this->getEntityManager();
        /** @var $q \Doctrine\ORM\Query */
        $q = $em->createQuery("SELECT n FROM SrNotesBundle:Note n WHERE n.type = :type AND n.pcAvancement < 100");
        $q->setParameters(array('type' => Note::TYPE_PROJET));
        $r = $q->getResult();
        return $r;
    }
}