<?php

namespace Sr\NotesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    /**
     * Supprime les tags qui ne sont utilisés par aucune note
     */
    public function nettoyerTags() {
        $em = $this->getEntityManager();
        /** @var $q \Doctrine\ORM\Query */
        $rsm = new \Doctrine\ORM\Query\ResultSetMapping();
        $q = $em->createNativeQuery("DELETE FROM Tag WHERE NOT EXISTS (SELECT 1 FROM note_tag WHERE tag_id = Tag.id)", $rsm);
        $q->execute();
    }
}